blank_issues_enabled: true
contact_links:
  - name: Questions and Help (on Stack Overflow)
    url: https://stackoverflow.com/questions/tagged/aptos
    about: Support and other Questions are handled by the team and the community on Stack Overflow.
  - name: Questions, Help and Chat (on Discord)
    url: https://discord.gg/aptosnetwork
    about: Contact the development team, contributors and community on Discord
